// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wlmhhlffetqqioondtre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsbWhobGZmZXRxcWlvb25kdHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NzI1NjQsImV4cCI6MjA3MjU0ODU2NH0.-tjanoJXA_cPRbXHknETKrSV2_AbMrfuWzua1t-JV4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});